### PR TITLE
Added GenerateQR.py

### PR DESCRIPTION
**Pull request by AJINKYA924**
Added code snip to Generate QR-Code with Python

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
If it's possible can you attach a screenshot of this script?

**Comment by AJINKYA924** [comment]
Added the QR code image for input link https://github.com/

**Comment by Mohamed-Ayaan358** [comment]
Is it possible for you store the two files on a  folder inside python?

**Comment by Mohamed-Ayaan358** [comment]
Good job on the commit @AJINKYA924 !

**Pull request merged**
