### PR TITLE
Create linkedlist.cpp

### PR DESCRIPTION
**Pull request by MayankRawat06**

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
This is basically just code for a linked list the purpose of this repository is to have small snippets below 50-100 lines so that users can contribute

**Comment by TishaJhabak1014** [comment]
Can I contribute by creating an issue. I would like to add a reusable snippet of code in python/ML domain. Thank you.
@Mohamed-Ayaan358

**Comment by Mohamed-Ayaan358** [comment]
> Can I contribute by creating an issue. I would like to add a reusable snippet of code in python/ML domain. Thank you. @Mohamed-Ayaan358

Sure you can

**Comment by TishaJhabak1014** [comment]
> > Can I contribute by creating an issue. I would like to add a reusable snippet of code in python/ML domain. Thank you. @Mohamed-Ayaan358
> 
> Sure you can
> Let me know if I can create an issue. That will be like a basic code structure we follow for ML model development.

**Comment by Mohamed-Ayaan358** [comment]
> basic code structure we follow for ML mod

Yes @TishaJhabak1014 you can

**Comment by Mohamed-Ayaan358** [comment]
i am now closing this pr

**Pull request closed without merging**
