### PR TITLE
Added file for issue #6

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
Adding basic codebase for ML model development in the form of .ipynb fiile.
Contributes to issue #6

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
This is quite a massive file is there any way that it can be cut down to smaller pieces that are more direct?

**Comment by Mohamed-Ayaan358** [comment]
And by any chance could you possibly explain this code as well as where it can be used brieflyy

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 

> This is quite a massive file is there any way that it can be cut down to smaller pieces that are more direct? @TishaJhabak1014

Well, It is quite simple though, I tried to include all necessary steps of ML model development. Please consider this.

**Comment by TishaJhabak1014** [comment]
> And by any chance could you possibly explain this code as well as where it can be used brieflyy

The code is quite well commented even for a beginner who at least knows the basics to implement ML.

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Also do let me know if I can add a file in the python folder for converting images to sketch. (This will surely be a small one ). Thank you.

**Comment by Mohamed-Ayaan358** [comment]
> @Mohamed-Ayaan358 Also do let me know if I can add a file in the python folder for converting images to sketch. (This will surely be a small one ). Thank you.

Well certainly do make a pull request and I'll check it out

**Comment by TishaJhabak1014** [comment]
> > @Mohamed-Ayaan358 Also do let me know if I can add a file in the python folder for converting images to sketch. (This will surely be a small one ). Thank you.
> 
> Well certainly do make a pull request and I'll check it out

Okay, can I create a issue for that?

**Comment by Mohamed-Ayaan358** [comment]
Ya u definitely can

**Comment by TishaJhabak1014** [comment]
Also if you strictly don't want to merge PR for #6 , do let me know. It will make a short snippet for handling missing values may be.

**Pull request merged**
