### PR TITLE
Added photo to sketch convertor

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
Contributes to issue #8

### CODE REVIEW

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Do check this, I hope it works : )

**Comment by Mohamed-Ayaan358** [comment]
Allright good job

**Comment by Mohamed-Ayaan358** [comment]
Can you confirm in some time if your PR is under review and keep me updated until the 15th? if it is finally accepted that is

**Comment by TishaJhabak1014** [comment]
> Can you confirm in some time if your PR is under review and keep me updated until the 15th? if it is finally accepted that is

Yes sure

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Also, plz plz do let me know if I need to rework on #6

**Comment by Mohamed-Ayaan358** [comment]
Ya it would be optimal if u could

**Comment by TishaJhabak1014** [comment]
> Ya, it would be optimal if u could.
> 
> Perhaps make it smaller for others to understand.

Making changes then.

**Pull request merged**
