### PR TITLE
Create express-boilerplate.js

### PR DESCRIPTION
**Pull request by kavin25**
Add Express.JS boilerplate

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
This is perhaps too basic is there any way that you can add to this program or other files that you can add? @kavin25

**Comment by kavin25** [comment]
@Mohamed-Ayaan358 Sure, will add a few lines to make it a basic CRUD

**Comment by Mohamed-Ayaan358** [comment]
Alright good job remember to hit the minimum requirement

**Comment by kavin25** [comment]
@Mohamed-Ayaan358 Added more stuff. There are 56 lines now

**Comment by Mohamed-Ayaan358** [comment]
Great job @kavin25 !

**Comment by Mohamed-Ayaan358** [comment]
@kavin25 Can I ask you favour can you see if your PR has been validated. I do believe that hactoberfest might take this repo as a spammy repo(cant really do anything abt it😂,cant find one place to get some legit PR's)

**Comment by kavin25** [comment]
@Mohamed-Ayaan358 Yes, it got counted

**Comment by Mohamed-Ayaan358** [comment]
Allright allright thanks man any updates please do pass it along

**Comment by Mohamed-Ayaan358** [comment]
> @Mohamed-Ayaan358 Yes, it got counted. Thank you

If by any chance if it does count under total completed could you shoot a message here?

**Pull request merged**
